version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: notion_db
    ports:
      - 5434:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=notion_db